[tool.poetry]
name = "elia-chat"
version = "0.1.0"
description = "A terminal interface to ChatGPT."
authors = ["Darren Burns <darrenb900@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
#textual = {version = ">=0.18.0", extras = ["dev"]}
openai = "^0.27.5"
textual = { path = "../textual", develop = true, extras = ["dev"] }
sqlmodel = "^0.0.8"
humanize = "^4.6.0"

[tool.poetry.scripts]
elia = "elia_chat.app:run"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.3.0"
types-peewee = "^3.16.0.0"
pre-commit = "^3.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
